/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @fileoverview High-Fidelity Security Metrics Engine (Client-Side BFF Architecture)
 * 
 * ARCHITECTURAL DESIGN:
 * This service implements a "Client-Side BFF" (Backend-for-Frontend) pattern,
 * using serverless-inspired heuristic algorithms to simulate complex SOC (Security
 * Operations Center) environments. It operates entirely in-memory, bypassing 
 * traditional DB/API requirements for static deployments while maintaining 
 * high-density telemetry.
 * 
 * CORE ALGORITHMS:
 * - Linear Interpolation (LERP) / Exponential Smoothing: Used for cinematic data transitions.
 * - Heuristic Event Generators: Simulates burst-mode threat patterns based on sensitivity thresholds.
 * - Deterministic Phase Stepper: Manages the 8-stage SOC lifecycle independently of UI locks.
 */

/** 
 * Severity Levels for Threat Events 
 */
export type ThreatLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

/** 
 * Operational Status for SOC Agents 
 */
export type AgentStatus = 'POLLING' | 'ANALYZING' | 'MITIGATING' | 'IDLE';

/** 
 * Standard 8-Stage SOC Lifecycle Phases 
 * Derived from NIST Cybersecurity Framework and industry best practices.
 */
export type SOCLifecyclePhase = 
  | 'MONITOR'       // Continuous telemetry stream observation
  | 'DETECT'        // Signature/Anomaly triggering
  | 'TRIAGE_L1'     // Level 1 filtering and false-positive reduction
  | 'ANALYSIS_L2'   // Deep forensic investigation
  | 'RESPONSE_L3'   // Active threat mitigation and isolation
  | 'RECOVERY'      // System restoration and patch deployment
  | 'HUNT'          // Proactive threat seeking in dormant nodes
  | 'LESSONS_LEARNT'; // Documentation and knowledge graph update

/**
 * Interface representing a Security Agent (Middleware/Orchestrator)
 */
export interface SecurityAgent {
  /** UUID or Shortname for the agent node */
  id: string;
  /** Display name of the service/middleware */
  name: string;
  /** Functional category within the SOC stack */
  type: 'DLP' | 'NETWORK' | 'ENDPOINT' | 'HEURISTIC';
  /** Current state in the Lifecycle */
  status: AgentStatus;
  /** Resource utilization percentage (0-100) */
  load: number;
  /** Most recent detected threat signature */
  lastDetection: string | null;
  /** Artificial intelligence health status */
  neuralHealth: number;
}

/**
 * Detailed Security Incident record
 */
export interface SecurityIncident {
  /** Global unique incident identifier */
  id: string;
  /** ISO timestamp of occurrence */
  timestamp: string;
  /** Categorized attack vector */
  type: 'SQL_INJECTION' | 'BRUTE_FORCE' | 'DLP_LEAK' | 'MALWARE_PHONING' | 'UNAUTHORIZED_ACCESS';
  /** Impact assessment */
  severity: ThreatLevel;
  /** Originator IP or Node identifier */
  source: string;
  /** Management status */
  status: 'OPEN' | 'INVESTIGATING' | 'RESOLVED';
  /** Natural language summary generated by the orchestration agent */
  summary: string;
}

/**
 * Key Performance Indicator for the global dashboard
 */
export interface SecurityKPI {
  label: string;
  value: number | string;
  trend: 'up' | 'down' | 'stable';
  color: 'matrix' | 'orange' | 'cyan' | 'red';
  /** Secondary supporting unit or metric */
  subValue?: string;
}

/**
 * Atomic Threat Event for high-frequency streams
 */
export interface ThreatEvent {
  id: string;
  type: string;
  source: string;
  severity: ThreatLevel;
  timestamp: string;
  /** Packet metadata or payload hash */
  meta?: string;
}

/**
 * Automated documentation report log
 */
export interface ReportLog {
  date: string;
  title: string;
  content: string;
  status: 'DRAFT' | 'FINALIZED';
}

/**
 * Global snapshot of the simulated environment state at a point in time.
 */
export interface MetricSnapshot {
  /** Epoch timestamp of the snap */
  timestamp: number;
  /** Synthesized global CPU load */
  cpu: number;
  /** Memory allocation profile */
  memory: {
    total: number;
    used: number;
    percentage: number;
    swap: number;
    cachePressure: number;
  };
  /** Network telemetry matrix */
  network: {
    rx: number; 
    tx: number; 
    activeConnections: number;
    threatScore: number;
    jitter: number;
    packetLoss: number;
  };
  /** I/O and Entropy metrics */
  disk: {
    read: number; 
    write: number; 
    iowait: number;
    entropy: number;
  };
  /** Active SOC agents */
  agents: SecurityAgent[];
  /** High-severity incidents in the current buffer */
  incidents: SecurityIncident[];
  /** Dashboard header KPIs */
  kpis: SecurityKPI[];
  /** historical threat trend (12h span) */
  threatsHistory: { time: string; count: number }[];
  
  // SOC Lifecycle & Orchestration State
  currentPhase: SOCLifecyclePhase;
  threatStream: ThreatEvent[];
  reportingAgent: ReportLog[];
  axeGuardStatus: 'ACTIVE' | 'ISOLATED' | 'BYPASS';
  /** LangGraph Orchestrator node tracking */
  langGraphNodes: { id: string; status: 'ACTIVE' | 'WAITING' | 'ERROR' }[];
}

/**
 * Control configuration for the simulation engine.
 */
export interface MetricsConfig {
  /** Frequency of malicious event generation (0-100) */
  sensitivity: number;
  /** Barrier for critical alarm triggering */
  threshold: number;
  /** Scaling for in-memory virtual agents */
  agentCount: number;
  /** Toggle for real-time telemetry pulse */
  realTimeMode: boolean;
  /** Multiplier for the 8-stage lifecycle rotation */
  lifecycleSpeed: number;
}

/**
 * MetricsEngine Class
 * 
 * An autonomous state-machine that simulates a heavy backend-oriented SOC environment.
 * Uses predictive algorithms to maintain a stable, high-fidelity experience without
 * external API dependencies.
 */
class MetricsEngine {
  private history: MetricSnapshot[] = [];
  private maxHistory = 60;
  private lastSnap: MetricSnapshot | null = null;
  private config: MetricsConfig = {
    sensitivity: 45,
    threshold: 75,
    agentCount: 4,
    realTimeMode: true,
    lifecycleSpeed: 3
  };

  private phases: SOCLifecyclePhase[] = [
    'MONITOR', 'DETECT', 'TRIAGE_L1', 'ANALYSIS_L2', 'RESPONSE_L3', 'RECOVERY', 'HUNT', 'LESSONS_LEARNT'
  ];
  private currentPhaseIdx = 0;
  private phaseTicks = 0;

  private rawThreats: ThreatEvent[] = [];
  private reportHistory: ReportLog[] = [
    { 
      date: '2026-04-17', 
      title: 'INCIDENT_RPT_#AS-124', 
      content: '# AXE-GUARD INCIDENT REPORT\n\n## STATUS: RESOLVED\nDetected unusual L7 egress pattern from secure enclave.\n\n### MITIGATION\nIsolated node #720 and flushed VNet caches.\n\n### LESSONS\nUpdate heuristics to detect fragment-level entropy shifts.',
      status: 'FINALIZED'
    }
  ];

  /**
   * Initializes the engine by backfilling historical data arrays
   * to ensure cold-starts have populated charts.
   */
  constructor() {
    this.initialize();
  }

  private initialize() {
    const now = Date.now();
    for (let i = 0; i < this.maxHistory; i++) {
      this.history.push(this.generateSnapshot(now - (this.maxHistory - i) * 60000));
    }
  }

  /**
   * Updates the global simulation configuration.
   * @param newConfig Partial config object to merge.
   */
  public setConfig(newConfig: Partial<MetricsConfig>) {
    this.config = { ...this.config, ...newConfig };
  }

  /**
   * Returns the current simulation configuration.
   */
  public getConfig() {
    return { ...this.config };
  }

  /**
   * Exponential Smoothing Algorithm
   * Used to prevent visual jitter in real-time data charts.
   * 
   * @param target The raw destination value.
   * @param current The current smoothed value.
   * @param factor Smoothing coefficient (lower = more stable/delayed).
   */
  private smooth(target: number, current: number, factor = 0.3) { 
    return (current * factor) + (target * (1 - factor));
  }

  /**
   * Central Heuristic Snapshot Generator
   * Deeply tuned to produce consistent, realistic SOC telemetry.
   * 
   * @param timestamp The time identifier for this data point.
   */
  private generateSnapshot(timestamp: number): MetricSnapshot {
    const { sensitivity, threshold, lifecycleSpeed } = this.config;
    const isBurst = Math.random() * 100 < sensitivity;
    
    // Lifecycle Logic - Advances through stages based on global speed
    this.phaseTicks++;
    if (this.phaseTicks > (30 / (lifecycleSpeed || 1))) {
      this.currentPhaseIdx = (this.currentPhaseIdx + 1) % this.phases.length;
      this.phaseTicks = 0;
    }

    const currentPhase = this.phases[this.currentPhaseIdx];

    // Malicious Event Generation Heuristic
    if (isBurst || Math.random() > 0.8) {
      const threatEvent: ThreatEvent = {
        id: 'EVT-' + Math.random().toString(36).substr(2, 5).toUpperCase(),
        type: currentPhase === 'DETECT' ? 'SIGNATURE_MATCH' : 'HEURISTIC_ANOMALY',
        source: `172.24.${Math.floor(Math.random()*10)}.${Math.floor(Math.random()*255)}`,
        severity: isBurst ? 'CRITICAL' : 'MEDIUM',
        timestamp: new Date().toISOString(),
        meta: `SHA256: 0x${Math.random().toString(16).substr(2, 12)}`
      };

      if (this.rawThreats.length > 20) this.rawThreats.shift();
      this.rawThreats.push(threatEvent);
    }

    // Serverless-Like Agent Distribution
    const agents: SecurityAgent[] = [
      { id: 'AXE-G', name: 'Axe-Guard-DLP', type: 'DLP', status: isBurst ? 'MITIGATING' : 'POLLING', load: 45 + Math.random() * 20, lastDetection: isBurst ? 'CORP-PII-EXFIL' : null, neuralHealth: 98.4 },
      { id: 'LGS-1', name: 'LangGraph-Orchestrator', type: 'HEURISTIC', status: 'ANALYZING', load: 60, lastDetection: null, neuralHealth: 99.9 },
      { id: 'PROM-V', name: 'Prometheus-Observer', type: 'NETWORK', status: 'POLLING', load: 20, lastDetection: null, neuralHealth: 88.2 }
    ];

    // Infrastructure synthesis (LERP applied to last state)
    const targetCpu = (isBurst ? 85 : 20) + Math.random() * 10;
    const cpu = this.lastSnap ? this.smooth(targetCpu, this.lastSnap.cpu) : targetCpu;

    const targetRx = 100 + Math.random() * 1000 + (isBurst ? 5000 : 0);
    const rx = this.lastSnap ? this.smooth(targetRx, this.lastSnap.network.rx) : targetRx;

    const targetTx = 50 + Math.random() * 500 + (isBurst ? 2000 : 0);
    const tx = this.lastSnap ? this.smooth(targetTx, this.lastSnap.network.tx) : targetTx;

    const targetEntropy = 0.2 + (Math.random() * 0.1) + (isBurst ? 0.3 : 0);
    const entropy = this.lastSnap ? this.smooth(targetEntropy, this.lastSnap.disk.entropy, 0.9) : targetEntropy;

    // Advanced Memory Synthesis
    const targetMemPercentage = 40 + (isBurst ? 30 : 0) + Math.random() * 5;
    const usedMem = (32 * targetMemPercentage) / 100;

    const snap: MetricSnapshot = {
      timestamp,
      cpu: Math.floor(cpu),
      memory: { 
        total: 32, 
        used: parseFloat(usedMem.toFixed(2)), 
        percentage: Math.floor(targetMemPercentage),
        swap: isBurst ? 2.4 : 0.8,
        cachePressure: 15 + Math.random() * 10
      },
      network: {
        rx: Math.floor(rx),
        tx: Math.floor(tx),
        activeConnections: 1200 + Math.floor(Math.random() * 200) + (isBurst ? 800 : 0),
        threatScore: isBurst ? 92 : 12,
        jitter: isBurst ? 12.4 : 1.2,
        packetLoss: isBurst ? 0.04 : 0
      },
      disk: { read: 10, write: 5, iowait: 0.1, entropy },
      agents,
      incidents: isBurst ? [{
        id: 'INC-' + Math.random().toString(36).substr(2, 4).toUpperCase(),
        timestamp: new Date().toISOString(),
        type: 'DLP_LEAK',
        severity: 'CRITICAL',
        source: 'INTERNAL_NODE_7_ZETA',
        status: 'OPEN',
        summary: 'Agentic LangGraph clusters identified PII leakage signatures in egress tunnel 0x42-B.'
      }] : [],
      kpis: [
        { label: 'SOC_PHASE', value: currentPhase, trend: 'stable', color: 'cyan', subValue: `Step ${this.phaseTicks}` },
        { label: 'AXE_SHIELD', value: (99.8 + Math.random() * 0.1).toFixed(2), trend: 'stable', color: 'matrix', subValue: 'Active Agents: 3' },
        { label: 'LLM_GUARD', value: 100, trend: 'up', color: 'matrix', subValue: 'Verified' }
      ],
      threatsHistory: Array.from({ length: 12 }, (_, j) => ({
        time: `${12 - j}h`,
        count: Math.floor(Math.random() * threshold) + (isBurst ? 40 : 0)
      })),
      
      currentPhase,
      threatStream: [...this.rawThreats],
      reportingAgent: this.reportHistory,
      axeGuardStatus: isBurst ? 'ISOLATED' : 'ACTIVE',
      langGraphNodes: [
        { id: 'L1_TRIAGE', status: 'ACTIVE' },
        { id: 'L2_ANALYSIS', status: currentPhase.includes('ANALYSIS') ? 'ACTIVE' : 'WAITING' },
        { id: 'L3_RESPONSE', status: currentPhase.includes('RESPONSE') ? 'ACTIVE' : 'WAITING' }
      ]
    };

    this.lastSnap = snap;
    return snap;
  }

  /**
   * Advances the simulation by one physical clock tick.
   * Generates new state and rotates the history buffer.
   * 
   * @returns The newly synthesized MetricSnapshot.
   */
  public tick(): MetricSnapshot {
    const next = this.generateSnapshot(Date.now());
    this.history.push(next);
    if (this.history.length > this.maxHistory) {
      this.history.shift();
    }
    return next;
  }

  /**
   * Returns the entire history buffer for charting long-tail trends.
   */
  public getHistory() {
    return [...this.history];
  }
}

/**
 * Singleton instance of the MetricsEngine.
 * Central Source of Truth for the SOC Dashboard.
 */
export const metricsService = new MetricsEngine();
