/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { motion } from 'motion/react';
import { ReportLog } from '../services/metricsService';
import { FileText, ChevronRight, Download, BookOpen } from 'lucide-react';

interface ReportingDocsProps {
  reports: ReportLog[];
}

/**
 * ReportingDocs Component
 * 
 * ARCHITECTURAL ROLE:
 * Static Knowledge Base & Incident Documentation Archive. This component simulates 
 * the persistent storage phase of the SOC lifecycle, rendering markdown logs 
 * generated by the orchestration logic.
 * 
 * DESIGN PATTERN:
 * Editorial Glassmorphism. Combines a structural file-tree navigation with 
 * a high-readability content viewer for technical incident reports.
 * 
 * DATA MAPPING:
 * Projects the `ReportLog` collection into a structured document viewer, 
 * simulating deep-turning around incident analysis.
 */
export default function ReportingDocs({ reports }: ReportingDocsProps) {
  const currentReport = reports[0];

  return (
    <div className="acrylic-card border-terminal-cyan/20 bg-black/40 h-full flex flex-col p-3 overflow-hidden">
      <div className="flex items-center justify-between mb-4 shrink-0">
        <div className="flex items-center gap-2">
          <BookOpen className="w-4 h-4 text-terminal-cyan" />
          <span className="text-[10px] uppercase text-terminal-cyan font-bold tracking-[0.2em] glow-text-cyan">
            ORCHESTRATION_&_DOCUMENTATION
          </span>
        </div>
        <div className="flex gap-2">
          <button className="p-1 hover:bg-white/5 rounded transition-colors">
            <Download className="w-3 h-3 text-white/40" />
          </button>
        </div>
      </div>

      <div className="flex flex-1 min-h-0 gap-4">
        {/* Navigation / File Tree */}
        <div className="w-40 border-r border-white/5 pr-4 flex flex-col gap-2 shrink-0">
          <span className="text-[8px] uppercase text-white/20 font-bold tracking-widest pl-2">Repository_v1</span>
          {reports.map((report, i) => (
            <motion.div
              key={i}
              className={`p-2 rounded cursor-pointer transition-all flex items-center gap-2 ${
                i === 0 ? 'bg-terminal-cyan/10 border border-terminal-cyan/20' : 'hover:bg-white/5'
              }`}
            >
              <FileText className={`w-3 h-3 ${i === 0 ? 'text-terminal-cyan' : 'text-white/30'}`} />
              <div className="flex flex-col min-w-0">
                <span className={`text-[8px] truncate font-bold ${i === 0 ? 'text-terminal-cyan' : 'text-white/60'}`}>
                  {report.title}
                </span>
                <span className="text-[7px] text-white/20 uppercase">{report.date}</span>
              </div>
            </motion.div>
          ))}
          <div className="mt-4 p-2 bg-neon-matrix/5 border border-neon-matrix/10 rounded">
             <span className="text-[7px] text-neon-matrix/60 font-mono italic leading-tight block">
               // Agentic documentation agent is currently distilling L1 findings...
             </span>
          </div>
        </div>

        {/* Content Viewer */}
        <div className="flex-1 bg-deep-void/40 rounded border border-white/5 p-4 overflow-hidden flex flex-col relative">
          <div className="absolute top-2 right-4 opacity-10">
            <ChevronRight className="w-12 h-12 text-terminal-cyan" />
          </div>
          
          <div className="tui-mono prose prose-invert max-w-none flex-1 overflow-y-auto custom-scrollbar pr-2">
            {/* Simple Markdown Simulation */}
            {currentReport.content.split('\n').map((line, idx) => {
              if (line.startsWith('# ')) return <h1 key={idx} className="text-terminal-cyan text-lg font-black mb-4 uppercase tracking-tighter">{line.replace('# ', '')}</h1>;
              if (line.startsWith('## ')) return <h2 key={idx} className="text-white font-bold text-sm mb-2 uppercase border-b border-white/10 pb-1 flex items-center gap-2"><ChevronRight className="w-3 h-3 text-neon-matrix" /> {line.replace('## ', '')}</h2>;
              if (line.startsWith('### ')) return <h3 key={idx} className="text-petro-orange text-xs font-bold mt-4 mb-2">{line.replace('### ', '')}</h3>;
              if (line === '') return <div key={idx} className="h-2" />;
              return <p key={idx} className="text-[11px] text-white/70 leading-relaxed mb-1">{line}</p>;
            })}
          </div>

          <div className="mt-8 pt-4 border-t border-white/5 text-[9px] text-white/20 flex justify-between items-center italic">
             <span>GEN_ID: 0x7FB-A2</span>
             <span className="uppercase">{currentReport.status}</span>
          </div>
        </div>
      </div>
    </div>
  );
}
